<?php

$products = $this->getData();


?>


<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>

   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</head>
<body>
	<?php require_once 'View/html/header.phtml';?>
    <div class="title9">
    	<div class="main9">MANAGE PRODUCTS</div>
    
    <div class="main99">
    	<a href="<?php echo $this->getUrl('product','add');?>" class="main999">ADD PRODUCT</a>
    </div>
    </div>
   <table class="table table-dark table-striped-columns">
   	     <tr align="center">
   	     	<td>Product_id</td>
   	     	<td>Name</td>
   	     	<td>Cost</td>
   	     	<td>SKU</td>
   	     	<td>Price</td>
   	     	<td>Quantity</td>
   	     	<td>Description</td>
   	     	<td>Status</td>
   	     	<td>Color</td>
   	     	<td>Material</td>
   	     	<td>Created_at</td>
   	     	<td>Updated_at</td>
   	     	<td>Media</td>
   	     	<td>EDIT</td>
   	     	<td>DELETE</td>
   	     </tr>

           <?php  if (!$products):?> 
              <tr>
                 <td>No records available.</td>
              </tr>
           <?php else:?>

   	      <?php foreach ($products as $product): ?>
            <tr align="center">
            	<td><?php echo $product->product_id; ?></td>
            	<td><?php echo $product->name; ?></td>
            	<td><?php echo $product->cost; ?></td>
            	<td><?php echo $product->SKU; ?></td>
            	<td><?php echo $product->price; ?></td>
            	<td><?php echo $product->quantity; ?></td>
            	<td><?php echo $product->description; ?></td>
               <td><?php echo $product->getStatusText; ($product->status);?></td>
            	<td><?php echo $product->color; ?></td>
            	<td><?php echo $product->material; ?></td>
            	<td><?php echo $product->created_at; ?></td>
            	<td><?php echo $product->updated_at; ?></td>
            	<td><a href="<?php echo $this->getUrl('product_media','grid',array('product_id' =>  $product->product_id));?>">media</td>
                  <td><a href="  <?php echo $this->getUrl('product','edit',array('product_id' =>  $product->product_id));?>">EDIT</td>
            	<td><a href="<?php echo $this->getUrl('product','delete',array('product_id' =>  $product->product_id));?>">DELETE</td>
            </tr>
   	     	
   	     <?php endforeach; ?>
           <?php endif; ?>
   </table>

</body>
</html>