<?php

$customer = $this->customer;
$address = $this->customerAddress;

?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link rel="stylesheet" type="text/css" href="Skin/CSS/cedit.css">
</head>
<body>
	<form action="<?php echo $this->getUrl('customer','save');?>" method="post">
		<div class="content9">
			<div class="add19">
				EDIT CUSTOMER				
			</div>
			<div class="add29">
				<a href="<?php echo $this->getUrl('customer','grid',[],true);?>" class="add39">Cancel</a>
				<button type="submit" class="add39">Save</button>
			</div>
		</div>
		<div class="head9">
			CUSTOMER INFORMATION
		</div>
		<table>
			<tr>
				<td>first_name</td>
				<td><input type="text" name="customer[first_name]" value="<?php echo $customer->first_name;?>" class="addi9"></td>
			</tr>
			<tr>
				<td>last_name</td>
				<td><input type="text" name="customer[last_name]" value=" <?php echo $customer->last_name; ?>" class="addi9"></td>
			</tr>
			<tr>
				<td>email</td>
				<td><input type="text" name="customer[email]" value=" <?php echo $customer->email; ?>" class="addi9"></td>
			</tr>
			<tr>
				<td>gender</td>
				<td><input type="text" name="customer[gender]" value=" <?php echo $customer->gender; ?>" class="addi9"></td>
			</tr>
			<tr>
				<td>mobile</td>
				<td><input type="text" name="customer[mobile]" value=" <?php echo $customer->mobile; ?>" class="addi9"></td>
			</tr>
			<!-- <tr>
				<td>status</td>
				<td>
					<select name="customer[status]" class="addi9" >
						<option value="active" <?php if ($customer->status === 'active'){echo "selected";}?>> active </option>
					
						<option value="inactive" <?php if ($customer->status === 'inactive'){echo "selected";}?>> inactive</option>
					</select>
				</td>
			</tr> -->
			<tr>
		<td>Status</td>
		<td>
		<select name="customer[status]">
			<?php foreach ($customer->getTable()->getStatusOptions() as $key => $value):?>
			<?php $selected = ($key == $customer->getstatus()) ? 'selected' : '';?>
			<option value="<?php echo $key ?>"<?php echo $selected; ?>><?php echo $value;?></option>
			<?php endforeach;?>
		</select>
	</td>
		<!-- <td><input type="text" name="admin[status]" value="<?php echo $admin->status ?>"></td> -->
	</tr>
		</table>
		<table>
		<tr>
			<td>address</td>
			<td><input type="text" name="address[address]"  class="addi9" value="<?php echo $address->address;?>"></td>
		</tr>
		<tr>
			<td>city</td>
			<td><input type="text" name="address[city]"  class="addi9" value="<?php echo $address->city;?>"></td>
		</tr>
		<tr>
			<td>state</td>
			<td><input type="text" name="address[state]"  class="addi9" value="<?php echo $address->state;?>"></td>
		</tr>
		<tr>
			<td>country</td>
			<td><input type="text" name="address[country]"  class="addi9" value="<?php echo $address->country;?>"></td>
		</tr>
		<tr>
			<td>zip_code</td>
			<td><input type="text" name="address[zip_code]"  class="addi9" value="<?php echo $address->zip_code;?>"></td>
		</tr>
	
	</table>
	</form>

</body>
</html>