<?php

$customers = $this->customers; 
echo "<pre>";
print_r($customers);
die();

?>


<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link rel="stylesheet" type="text/css" href="Skin/CSS/cgrid.css">
</head>
<body>
<?php require_once 'View/html/header.phtml';?>
 <div class="title9">
 	<div class="main9">
 		MANAGE CUSTOMER
 	</div>
 	<div class="main99">
 		<a href="<?php echo $this->getUrl('customer','add');?>" class="main999">ADD CUSTOMER</a>
 	</div>
 </div>
 <table>
 	<tr>
 		<td>customer_id</td>
 		<td>first_name</td>
 		<td>last_name</td>
 		<td>email</td>
 		<td>gender</td>
 		<td>mobile</td>
 		<td>status</td>
 		<td>created_at</td>
 		<td>updated_at</td>
 		<td>EDIT</td>
 		<td>DELETE</td>
 	</tr>
 	<?php if (!$customers):?>
		<tr>
			<td>No records available.</td>
		</tr>
	<?php else:?>
 	<?php foreach ($customers as $customer):?> 
 		<tr>
 			<td><?php echo $customer->customer_id;?></td>
 			<td><?php echo $customer->first_name;?></td>
 			<td><?php echo $customer->last_name;?></td>
 			<td><?php echo $customer->email;?></td>
 			<td><?php echo $customer->gender;?></td>
 			<td><?php echo $customer->mobile;?></td>
 			<!-- <td><?php echo $customer->status;?></td> -->
			<td><?php echo $customer->getStatusText($customer->status );?></td>
 			<td><?php echo $customer->created_at;?></td>
 			<td><?php echo $customer->updated_at;?></td>
 			<td><a href="<?php echo $this->getUrl('customer','edit',array('customer_id' =>  $customer->customer_id));?>">EDIT</td>
 			<td><a href="<?php echo $this->getUrl('customer','delete',array('customer_id' =>  $customer->customer_id));?>">DELETE</td>
 		</tr>
 	<?php endforeach;?>
 	<?php endif;?>
 </table>
</body>
</html>