<?php 
$categories = $this->getCategories();
?>

<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Manage Category</title>
	<link rel="stylesheet" type="text/css" href="skin/css/grid.css">
</head>


	<body>
		<div class="head_container">
		    <h2	class="logo">MANAGE CATEGORIES</h2>
		    <a class="add_btn" href="index.php?c=category&a=add">ADD CATEGORY</a>
		</div>
		<div class="tabel_container">
		    <table >
		        <tr>
		            <th>Category ID</th>
		            <th>Name</th>
		            <th>Status</th>
		            <th>Description</th>
		            <th>Created At</th>
		            <th>Updated At</th>
		            <th>EDIT</th>
		            <th>DELETE</th>
		        </tr>
		        <?php 
		        foreach ($categories as $category) {   
		        ?>
		        <tr>
		            <td><?php echo $category["category_id"]; ?></td>
		            <td><?php echo $category["name"]; ?></td>
		            <td><?php echo $category["status"]; ?></td>
		            <td><?php echo $category["description"]; ?></td>
		            <td><?php echo $category["created_at"]; ?></td>
		            <td><?php echo $category["updated_at"]; ?></td>
		            <td><a  style="text-decoration:none;" href="index.php?c=category&a=edit&category_id=<?php echo $category["category_id"]; ?>">Edit</a></td>
		            <td><a  style="text-decoration:none;" href="index.php?c=category&a=delete&category_id=<?php echo $category["category_id"]; ?>">Delete</a></td>
		        </tr>
		        <?php
		        }
		        ?>
		    </table>
		</div>
		<div>
		    <?php require_once 'View/html/footer.phtml'; ?>
		</div>
	</body>
</html>