<?php

$shippingMethod = $this->shipping;
// $shippingId = $this->getShippingId();

?>




<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link rel="stylesheet" type="text/css" href="Skin/CSS/cedit.css">
</head>
<body>
	<form action="<?php echo $this->getUrl('shipping','save');?>" method = "post">
		<div class="content9">
			<div class="add19">
				EDIT SHIPPING
			</div>
			<div class="add29">
				<a href="<?php echo $this->getUrl('shipping','grid',[],true);?>" class="add39">Cancel</a>
				<button type="submit" class="add39">Save</button>
			</div>
		</div>
		<div class="head9">
			SHIPPING INFORMATION
		</div>

		<table>
			<tr>
				<td>name</td>
				<td><input type="text" name="shipping[name]" value="<?php echo $shippingMethod->name;?>" class = "addi9">
				</td>
			</tr>
			<tr>
				<td>amount</td>
				<td><input type="text" name="shipping[amount]" value="<?php echo $shippingMethod->amount;?>" class = "addi9">
				</td>
			</tr>
				<tr>
		<td>Status</td>
		<td>
		<select name="shipping[status]">
			<?php foreach ($shippingMethod->getTable()->getStatusOptions() as $key => $value):?>
			<?php $selected = ($key == $shippingMethod->getstatus()) ? 'selected' : '';?>
			<option value="<?php echo $key ?>"<?php echo $selected; ?>><?php echo $value;?></option>
			<?php endforeach;?>
		</select>
	</td>
		<!-- <td><input type="text" name="admin[status]" value="<?php echo $admin->status ?>"></td> -->
	</tr>
		</table>
	</form>
</body>
</html>